mazo = {"esp_1" : {"valor" : 1,
                 "valor_real" : 14,
                 "palo": "espada",
                 "envido": 1},
        "esp_2" : {"valor" : 2,
                 "valor_real" : 9,
                 "palo": "espada",
                 "envido": 2},
        "esp_3" : {"valor" : 3,
                 "valor_real" : 10,
                 "palo": "espada",
                 "envido": 3},
        "esp_4": {"valor" : 4,
                 "valor_real" : 1,
                 "palo": "espada",
                 "envido": 4},
        "esp_5": {"valor" : 5,
                 "valor_real" : 2,
                 "palo": "espada",
                 "envido": 5},
        "esp_6": {"valor" : 6,
                 "valor_real" : 3,
                 "palo": "espada",
                 "envido": 6},
        "esp_7": {"valor" : 7,
                 "valor_real" : 12,
                 "palo": "espada",
                 "envido": 7},
        "esp_10": {"valor" : 10,
                 "valor_real" : 5,
                 "palo": "espada",
                 "envido": 0},
        "esp_11": {"valor" : 11,
                 "valor_real" : 6,
                 "palo": "espada",
                 "envido": 6},
        "esp_12": {"valor" : 12,
                 "valor_real" : 7,
                 "palo": "espada",
                 "envido": 0},
        "bas_1": {"valor" : 1,
                 "valor_real" : 13,
                 "palo": "basto",
                 "envido": 1},
        "bas_2": {"valor" : 2,
                 "valor_real" : 9,
                 "palo": "basto",
                 "envido": 2},
        "bas_3": {"valor" : 3,
                 "valor_real" : 10,
                 "palo": "basto",
                 "envido": 3},
        "bas_4": {"valor" : 4,
                 "valor_real" : 1,
                 "palo": "basto",
                 "envido": 4},
        "bas_5": {"valor" : 5,
                 "valor_real" : 2,
                 "palo": "basto",
                 "envido": 5},
        "bas_6": {"valor" : 6,
                 "valor_real" : 3,
                 "palo": "basto",
                 "envido": 6},
        "bas_7": {"valor" : 7,
                 "valor_real" : 4,
                 "palo": "basto",
                 "envido": 7},
        "bas_10": {"valor" : 10,
                 "valor_real" : 5,
                 "palo": "basto",
                 "envido": 0},
        "bas_11": {"valor" : 11,
                 "valor_real" : 6,
                 "palo": "basto",
                 "envido": 0},
        "bas_12": {"valor" : 12,
                 "valor_real" : 7,
                 "palo": "basto",
                 "envido": 0},
        "oro_1": {"valor" : 1,
                 "valor_real" : 8,
                 "palo": "oro",
                 "envido": 1},
        "oro_2": {"valor" : 2,
                 "valor_real" : 9,
                 "palo": "oro",
                 "envido": 2},
        "oro_3": {"valor" : 3,
                 "valor_real" : 10,
                 "palo": "oro",
                 "envido": 3},
        "oro_4": {"valor" : 4,
                 "valor_real" : 1,
                 "palo": "oro",
                 "envido": 4},
        "oro_5": {"valor" : 5,
                 "valor_real" : 2,
                 "palo": "oro",
                 "envido": 5},
        "oro_6": {"valor" : 6,
                 "valor_real" : 3,
                 "palo": "oro",
                 "envido": 6},
        "oro_7": {"valor" : 7,
                 "valor_real" : 11,
                 "palo": "oro",
                 "envido": 7},
        "oro_10": {"valor" : 10,
                 "valor_real" : 5,
                 "palo": "oro",
                 "envido": 0},
        "oro_11": {"valor" : 11,
                 "valor_real" : 6,
                 "palo": "oro",
                 "envido": 0},
        "oro_12": {"valor" : 12,
                 "valor_real" : 7,
                 "palo": "oro",
                 "envido": 0},
        "cop_1": {"valor" : 1,
                 "valor_real" : 8,
                 "palo": "copa",
                 "envido": 1},
        "cop_2": {"valor" : 2,
                 "valor_real" : 9,
                 "palo": "copa",
                 "envido": 2},
        "cop_3": {"valor" : 3,
                 "valor_real" : 10,
                 "palo": "copa",
                 "envido": 3},
        "cop_4": {"valor" : 4,
                 "valor_real" : 1,
                 "palo": "copa",
                 "envido": 4},
        "cop_5": {"valor" : 5,
                 "valor_real" : 2,
                 "palo": "copa",
                 "envido": 5},
        "cop_6": {"valor" : 6,
                 "valor_real" : 3,
                 "palo": "copa",
                 "envido": 6},
        "cop_7": {"valor" : 7,
                 "valor_real" : 4,
                 "palo": "copa",
                 "envido": 7},
        "cop_10": {"valor" : 10,
                 "valor_real" : 5,
                 "palo": "copa",
                 "envido": 0},
        "cop_11": {"valor" : 11,
                 "valor_real" : 6,
                 "palo": "copa",
                 "envido": 0},
        "cop_12": {"valor" : 12,
                 "valor_real" : 7,
                 "palo": "copa",
                 "envido": 0},}